### PR TITLE
#161153411 Fix broken links and add javascript functionality 

### PR DESCRIPTION
**Pull request by SelaDanti**
**What does this PR do?**
Fix the broke links 
Implement feedback

**Description of task accomlished?**
Added javascript code to redirect the buttons
Added javascript code to alter html DOM

**How shouls this app be manually tested?**
Clone this repo to your local machine
view the UI

**What are the relevant Pivotal tracker stories?**
[#161153411](https://www.pivotaltracker.com/story/show/161153411)

**Sample screenshot**
Login
screenshot from 2018-10-11 22-57-52

Attendants 
screenshot from 2018-10-11 22-58-06

screenshot from 2018-10-11 22-58-34

Admin
screenshot from 2018-10-11 22-58-57

screenshot from 2018-10-11 22-59-18

### CODE REVIEW

**Comment by Paulstar200** [comment]
This looks good. Maybe just edit the login form where you've written **administrator, store attendant**. You can replace the **,** with a **|** .

**Comment by eduhmik** [comment]
Naona usiku sacco tuko wengi

**Comment by eduhmik** [comment]
Nice workbro

**Comment by eduhmik** [comment]
Edit user to me seems a bit cluttered

**Pull request merged**
