### PR TITLE
#16104088 Create a login page

### PR DESCRIPTION
**Pull request by SelaDanti**
**What does this PR do?**

Creates a Login Page for both admin and store attendant

**Description of task completed**

1. Created folder structure for the UI
2. Add css Styling for Login page
3. Add html for Login page

**How should this be manually tested**

Clone the repo to your local machine
Click on index.html and view the UI

**What are the relevant Pivotal Tracker Stories**
[#161040881](https://www.pivotaltracker.com/story/show/161040881)

screenshot from 2018-10-10 18-54-23

### CODE REVIEW

**Comment by waracci** [comment]
1. Great PR outline
2. Your form lacks labels to the inputs (Is this by design?).  Also try to state what the login form is for(you could say "login to store-manager").
3. A great colour combination and good use of an image above the login form.

**Comment by SelaDanti** [comment]
> 1. Great PR outline
> 2. Your form lacks labels to the inputs (Is this by design?).  Also try to state what the login form is for(you could say "login to store-manager").
> 3. A great colour combination and good use of an image above the login form.

@waracci  Thank you for the feedback. Yes the labels are by design and i plan on sorting the user roles in the back end not the front end

**Comment by BoltC0rt3z** [comment]
The PR Outline is awesome
I would recommend you add label at the top to indicate the login page is for what exactly like the name of the Store or just Store Manager.

**Comment by kwanj-k** [comment]
Nice implementation
but your PR is to master.....

**Comment by sharkdevs** [comment]
@SelaDanti I think its fine.. Only Indicate something to do with Login in that interface as @BoltC0rt3z  mentioned

**Comment by SelaDanti** [comment]
> @SelaDanti I think its fine.. Only Indicate something to do with Login in that interface as @BoltC0rt3z mentioned

Will do so.

**Comment by eduhmik** [comment]
Nice styling
Consider adding a link to recover password for the user

**Comment by Paulstar200** [comment]
This is good. But we need some labels or description for the page. e.g Storemanager because I can see it's the index.html page.

**Pull request merged**
